### ISSUE TITLE
updating /tracts json for tractview v2

### ISSUE THREAD

**Issue by soichih** [DanNBullock/wma_tools#1]
@DanNBullock 

Can you add round() to the tracts json output so that each values are rounded at the 2nd decimal point? This significantly reduces the tract json file sizes, and 3rd and above decimal points doesn't provide any values to the visualizer.

**Comment by DanNBullock** [comment]
is this done?  Does this need to be dealt with still?

**Comment by soichih** [comment]
Here is the latest tract.json output from app-wmaSeg (v1.9)

```
[17.38,17.669,18.017,18.312,18.387,18.231,18.056,
```

I think it's working!
