### ISSUE TITLE
wmaSeg output failing (new) validator-neuro-wmc

### ISSUE THREAD

**Issue by soichih** [DanNBullock/wma_tools#17]
I just recompiled app-wmaSeg with the latest version of wma_tools. According to our current implementation of validator-neuro-wmc, the output classification.mat is failing the following checks.

* Error All names must be all unique. 
duplicates:leftpArc,rightpArc,leftContraMotorCerebellar,rightContraMotorCerebellar,leftContraAnterioFrontoCerebellar,rightContraAnterioFrontoCerebellar
* Warning The name 'left AnterioFrontoCerebellar' should not contain whitespace
* Warning The name 'right AnterioFrontoCerebellar' should not contain whitespace

I believe these issues need to be fixed in wma_tools.

**Comment by francopestilli** [comment]
@DanNBullock can you please make a test on your code to see whether perhaps you left in double copies of some of the fields and have names with spaces?

**Comment by DanNBullock** [comment]
Could you link me to a classification structure that has this feature?
This strikes me as somewhat improbable?  Theoretically my code does not
permit this

https://github.com/DanNBullock/wma_tools/blob/f29f90faeaca61df7fb222c181f6951a5284064c/ClassificationStruc_Tools/bsc_reconcileClassifications.m#L36

**Comment by DanNBullock** [comment]
The spaces bit, yes is something that I need to change, but the duplicates
I'm not sure about.

**Comment by DanNBullock** [comment]
Also, wouldn't > duplicates:leftpArc,rightpArc,leftContraMotorCerebellar,rightContraMotorCerebellar,leftContraAnterioFrontoCerebellar,rightContraAnterioFrontoCerebellar

result in duplicate entires on the visualizer?

**Comment by DanNBullock** [comment]
@soichih I think it may have something to do with the change made here: https://github.com/DanNBullock/wma_tools/commit/5afa5e252c9cd15e52ee5535e5e697b007184bab

You may want to check and see if older branches of wma_seg reflect this.  If I recall correctly, old versions of that segmentation only output 61 or 62 tracts (not 69) so, I think this redundancy output is a new behavior.

**Comment by DanNBullock** [comment]
> Warning The name 'left AnterioFrontoCerebellar' should not contain whitespace
> Warning` The name 'right AnterioFrontoCerebellar' should not contain whitespace

Fixed:  https://github.com/DanNBullock/wma_tools/commit/f1a3cd5f73d7dda653017b99fd70cc9999ee9498

**Comment by francopestilli** [comment]
@soichih @DanNBullock @bacaron I suggest requiring camelCase for all brainlife.io/datattypes https://en.wikipedia.org/wiki/Camel_case

**Comment by DanNBullock** [comment]
@francopestilli 
are you recommending a standard for the tract names of the WMC datatype?  I think previously we were doing the data specification in the validator repo () but now there seems to be a separate site for it (https://brainlife.io/datatype/5cc1d64c44947d8aea6b2d8b) I'm not sure how to access a github repo for that document though (where you could make an issue for this).

I think I've had this adopted with my tract names for a while now (the current exception not withstanding).  I'm not sure how other people have been doing it.  I think my category segmentation separates the [side] designator (left/right) with an underscore ('_') just for clarity.

**Comment by DanNBullock** [comment]
https://github.com/DanNBullock/wma_tools/commit/9edbe42bbf1b1698206db0c2d5ea1256263e125e

Appears to have fixed it

**Comment by soichih** [comment]
I've confirmed that the update fixed all the validation issues.
