### ISSUE TITLE
too many inputs for the function

### ISSUE THREAD

**Issue by kitchell** [DanNBullock/wma_tools#3]
https://github.com/DanNBullock/wma_tools/blob/3929069be460eceba21a3bb8c52a2b6bf6a98c1a/bsc_LoadAndParseFiberStructure.m#L27

this function currently only takes a filepath as input. not sure what the .5 is for.

**Comment by DanNBullock** [comment]
You're right.  I think this was a quick and dirty find and replace job from the previous function, which had an optional input which corresponded to the sampling rate of the loaded tck.  .5 would have been 1 node per .5 mm I think.

Solution = delete additional input.

**Comment by bacaron** [comment]
this is still an issue....

**Comment by DanNBullock** [comment]
Should be fixed at this point, although I think soichi's version of the app doesn't even use this wrapper any more.

I dont have a permalink for it but it is either fgRead or dtiImportFibersMrtrix that has been modified (I think the overarching purpose was to reduce memory usage).

Example implimentation:  https://github.com/brainlife/app-wmaSeg/blob/c94f11dfd00b6de69a12a1e1ef9c1ec2b1f9b73f/main.m#L11
